### ISSUE TITLE
Through-hole parts

### ISSUE THREAD

**Issue by gbraad** [laneboysrc/rc-simple-switch#1]
All the parts are easy to replace with through hole components. What would be the suggested alternative for the PMV30UN?

**Comment by laneboysrc** [comment]
I don't have any experience with through-hole parts. 
Basically what you need is a MOSFET that is "logic-level", i.e. it has a very low Vgs threshold.
An example that seems to fit the spec: Fairchild FQP30N06L,

**Comment by gbraad** [comment]
Thanks, so either a FQP30N06L or IRLB8721 will do, driven from the gate.
